### ISSUE TITLE
Got unsatisfactory results when detecting poison/trojan data

### ISSUE THREAD

**Issue by MinqiShao** [wanlunsec/Beatrix#1]
Hi, thank you for your well done work and sharing code with public~
However, when I tried to use your code to detect poison data by using my own IAD backdoor models(including mnist, cifar10, gtsrb), I got some results that seemed not very good. Specifically, the picture is the result of mnist and 2Conv+2Dense model, target class is 0 and I utilized the output of penultimate dense layer.
'true_positive_95' and 'true_positive_99' are computed according to your related code. (my IAD train and eval code is almost like yours)
I trained cifar10 and gtsrb on Resnet18 but also got bad results.(using the output of last conv layer)
Can you offer some help to me? :)

<img width="374" alt="image" src="https://user-images.githubusercontent.com/79695208/205048062-30a49493-9f0b-4614-a86a-89997e54afa2.png">

**Comment by wanlunsec** [comment]
Hi MinqiShao,

I have checked the code and found that I wrongly deleted a line of code when preparing a clear version of the code. 
This line of code is corresponding to Equation.8 in the paper.
https://github.com/wanlunsec/Beatrix/blob/88423c002c1b347aa6f00087959e656b93b7c029/defenses/Beatrix/Beatrix.py#L336 

We didn't evaluate on MNIST, but you may try to use the output of the shallower layer since features may be heavily entangled in the last layers. 

Cheers,
Wanlun

**Comment by MinqiShao** [comment]
Thank you for your quick response and check, Wanlun.
I will use the revised version and features of other layers to do my experiments again.🙇‍♀️

Thanks again! :)
