### ISSUE TITLE
Got weird problem when running Beatrix.py

### ISSUE THREAD

**Issue by lui1343** [wanlunsec/Beatrix#2]
Thank you for your work and code!
I noticed your code have mentioned about celeba dataset,so i tried to run the code on celeba dataset.When i run train.py, some config seems weird, like Clean Accuracy:0.000, Cross Accuracy:0.000.
When i run Beatrix.py, i set clean_data_perclass = 1, but there is some error: 
RuntimeError: cannot reshape tensor of 0 elements into shape [0, 256, -1] because the unspecified dimension size -1 can be any value and is ambiguous.
I skipped empty data, but at last the J_t is empty.
I am a rookie in that area, if you are free, can you offer some help about this? Thanks for you time!
Here is my email: 23210240170@m.fudan.edu.cn

**Comment by wanlunsec** [comment]
Thank you for reaching out and for your interest in our work. 

Please note that the code we provided is a modified version of the original code released by the authors of the Input-Aware Dynamic Backdoor Attack (NeurIPS'20) [[code](https://github.com/VinAIResearch/input-aware-backdoor-attack-release)]. Since we did not conduct experiments on the CelebA dataset in our paper, we did not specifically test our code on CelebA. Therefore, we may not be able to provide detailed assistance specifically related to running the code on CelebA.

**Comment by lui1343** [comment]
Thanks for you time!
By the way, I still have problems in Beatrix/classifier_models/preact_resnet.py.  In class PreActResNet, line 83:
self.linear = nn.Linear(512 * block.expansion, num_classes)
I need to change the parameter 512 when I using different datasets, or it will go wrong because two matrix's shape don't match. Is it normal to need to change the parameter here depending on the dataset? If you know the details about it, please offer me some help.
Thanks for you time again!

**Comment by wanlunsec** [comment]
Hi,

The network architecture of PreActResNet is already predefined in classifier_models/preact_resnet.py. 

If you want to train PreActResNet on different datasets, you only need to set an appropriate "num_classes" in 
https://github.com/wanlunsec/Beatrix/blob/685827e3aa3c8090ab31b32bff898a877a9cd11d/classifier_models/preact_resnet.py#L124
 
Or, if you want to train a larger model, we can choose to use the model architecture with more layers, such as PreActResNet34, 
https://github.com/wanlunsec/Beatrix/blob/685827e3aa3c8090ab31b32bff898a877a9cd11d/classifier_models/preact_resnet.py#L128

Hope this information can help you.

**Comment by lui1343** [comment]
Thank you wanlun, your reply helps me a lot ,i have successfully ran the code.
